#' BDNCP open data from ANAC
#'
#' available data can be consulted and downloaded through the
#' appropriate subsections; in particular, in the "Analytics" section
#' there is a dashboard for browsing and analyzing data on public contracts,
#' while in the "Dataset" section a series of freely downloadable
#' JSON and CSV and XML files are available.
#'
#' @format ## `who`
#' A data frame with 7,240 rows and 60 columns:
#' \describe{
#'   \item{cig, cig_accordo_quadro}{alphanumeric code generated by the ANAC SIMOG system}
#'   \item{numero_gara, oggetto_gara}{bidding related info}
#'   \item{importo_complessivo_gara}{bidding amount}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   \item{year}{Year}
#'   ...
#' }
#' @source <https://dati.anticorruzione.it/opendata>
"mock_data_core"
